### ISSUE TITLE
Error on creating an org

### ISSUE THREAD

**Issue by leviadam** [daostack/Alchemy-Aurelia#1]
When deploying a new org I'm getting:
```Transaction Error. Exception thrown in contract code.```

**Comment by dkent600** [comment]
@leviadam Where are you seeing this?  In the Kovan transaction popup or only in the application?

I just created a DAO without incident, so it would be great to know how you had your organization configured?  (Founders, schemes, voting config, etc?)  A screenshot of the config would be great.

It might also be helpful to have the address of the failing transaction.  I would try to run the truffle debugger on it.

**Comment by leviadam** [comment]
I see it in the metamask popup.
You can see the TXs history here:
https://kovan.etherscan.io/address/0xf16294a979a027f297dace2f618cb57bc4bf5d16

**Comment by dkent600** [comment]
@leviadam Are there any clues you can give me as to how you configured the Dao, to help us be able to reproduce it?

**Comment by leviadam** [comment]
I think I used the default config.

**Comment by dkent600** [comment]
Thanks @leviadam.  Have you ever been able to birth a Dao, using Alchemy, without an error?  _Ie_, is this consistent for you, or intermittent?

**Comment by leviadam** [comment]
I think I was able to in the past. But I already got this error before.

**Comment by dkent600** [comment]
Saving for later, just in case:

![image](https://user-images.githubusercontent.com/1821666/33435008-0b5e31a6-d5af-11e7-9f83-1862bc598b0e.png)

**Comment by dkent600** [comment]
For what it's worth, starting yesterday I have seen an intermittent issue when creating a Dao against *testrpc* that actually crashes testrpc!  The error:

"Cannot read property 'pop' of undefined"

**Comment by dkent600** [comment]
I think we should close this until someone comes up with a repro.
